tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      export apiadd="https://9090-${GITPOD_WORKSPACE_URL##https://}" && docker-compose up
ports:
  - port: 9090
    visibility: public

